// Registry of bundled alert tunes. Files are generated by scripts/gen-sounds.mjs
// and served from public/sounds/. All are original/CC0 (see ASSETS.md).

export type Sound = { id: string; label: string; file: string };

export const SOUNDS: Sound[] = [
  { id: "chime", label: "Chime", file: "/sounds/chime.wav" },
  { id: "bell", label: "Bell", file: "/sounds/bell.wav" },
  { id: "ping", label: "Ping", file: "/sounds/ping.wav" },
  { id: "marimba", label: "Marimba", file: "/sounds/marimba.wav" },
  { id: "pulse", label: "Pulse", file: "/sounds/pulse.wav" },
];

export const DEFAULT_SOUND_ID = "chime";

export function play(soundId: string, volume: number) {
  const sound = SOUNDS.find((s) => s.id === soundId) ?? SOUNDS[0];
  const audio = new Audio(sound.file);
  audio.volume = Math.max(0, Math.min(1, volume));
  void audio.play().catch(() => {
    /* autoplay can be blocked until first interaction; ignore */
  });
}
