// Registry of bundled alert tunes. Files are generated by scripts/gen-sounds.mjs
// and served from public/sounds/. All are original/CC0 (see ASSETS.md).

export type Sound = { id: string; label: string; file: string };

export const SOUNDS: Sound[] = [
  { id: "chime", label: "Chime", file: "/sounds/chime.wav" },
  { id: "pulse", label: "Pulse", file: "/sounds/pulse.wav" },
  // Longer (3-4s), modern tones.
  { id: "bloom", label: "Bloom", file: "/sounds/bloom.wav" },
  { id: "aurora", label: "Aurora", file: "/sounds/aurora.wav" },
  { id: "cascade", label: "Cascade", file: "/sounds/cascade.wav" },
  { id: "kalimba", label: "Kalimba", file: "/sounds/kalimba.wav" },
  { id: "bowl", label: "Singing Bowl", file: "/sounds/bowl.wav" },
  { id: "notify", label: "Notify", file: "/sounds/notify.wav" },
  { id: "flute", label: "Flute", file: "/sounds/flute.wav" },
  { id: "techno", label: "Techno", file: "/sounds/techno.wav" },
  { id: "drum", label: "Drum", file: "/sounds/drum.wav" },
  { id: "neon", label: "Neon", file: "/sounds/neon.wav" },
  { id: "arcade", label: "Arcade", file: "/sounds/arcade.wav" },
  { id: "cartoon", label: "Cartoon", file: "/sounds/cartoon.wav" },
];

export const DEFAULT_SOUND_ID = "chime";

// Neutralize the macOS media keys for our alert. An <audio> element makes the
// page the "Now Playing" target, so the play/pause key (F8) would replay the
// tone. Installing no-op media-session handlers overrides that default so the
// media key does nothing to us.
if (typeof navigator !== "undefined" && "mediaSession" in navigator) {
  const noop = () => {};
  const actions: MediaSessionAction[] = [
    "play",
    "pause",
    "stop",
    "previoustrack",
    "nexttrack",
    "seekbackward",
    "seekforward",
  ];
  for (const a of actions) {
    try {
      navigator.mediaSession.setActionHandler(a, noop);
    } catch {
      /* action not supported on this platform */
    }
  }
}

// Single shared player so a new tone never overlaps a still-ringing one
// (overlap comb-filters into an echoey/reverbed sound).
let current: HTMLAudioElement | null = null;

export function play(soundId: string, volume: number) {
  const sound = SOUNDS.find((s) => s.id === soundId) ?? SOUNDS[0];
  if (current) {
    current.pause();
    current.currentTime = 0;
  }
  const audio = new Audio(sound.file);
  audio.volume = Math.max(0, Math.min(1, volume));
  current = audio;
  void audio.play().catch(() => {
    /* autoplay can be blocked until first interaction; ignore */
  });
}
