//! Tray icon, menu, popover toggling, and OS notifications.

use tauri::menu::{Menu, MenuItem, PredefinedMenuItem};
use tauri::tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent};
use tauri::{AppHandle, Emitter, Manager, PhysicalPosition};
use tauri_plugin_notification::NotificationExt;

use crate::timer::{fmt_mmss, PhaseChange, TimerSnapshot};
use crate::AppState;

const TRAY_ID: &str = "main-tray";

/// Monochrome clock icon (generated by scripts/gen-tray-icon.mjs). Used as a
/// macOS template image so the system tints it for the menu-bar appearance.
const TRAY_ICON: &[u8] = include_bytes!("../icons/tray.png");

pub fn build_tray(app: &AppHandle) -> tauri::Result<()> {
    let start_pause = MenuItem::with_id(app, "start_pause", "Start / Pause", true, None::<&str>)?;
    let reset = MenuItem::with_id(app, "reset", "Reset", true, None::<&str>)?;
    let skip = MenuItem::with_id(app, "skip", "Skip", true, None::<&str>)?;
    let sep1 = PredefinedMenuItem::separator(app)?;
    let stats = MenuItem::with_id(app, "open_stats", "Open Stats", true, None::<&str>)?;
    let settings = MenuItem::with_id(app, "open_settings", "Settings", true, None::<&str>)?;
    let sep2 = PredefinedMenuItem::separator(app)?;
    let quit = MenuItem::with_id(app, "quit", "Quit Timelon", true, None::<&str>)?;

    let menu = Menu::with_items(
        app,
        &[
            &start_pause,
            &reset,
            &skip,
            &sep1,
            &stats,
            &settings,
            &sep2,
            &quit,
        ],
    )?;

    let icon = tauri::image::Image::from_bytes(TRAY_ICON)?;
    let builder = TrayIconBuilder::with_id(TRAY_ID)
        .icon(icon)
        .icon_as_template(true)
        .menu(&menu)
        .show_menu_on_left_click(false)
        .on_menu_event(|app, event| handle_menu(app, event.id.as_ref()))
        .on_tray_icon_event(|tray, event| {
            if let TrayIconEvent::Click {
                button: MouseButton::Left,
                button_state: MouseButtonState::Up,
                position,
                ..
            } = event
            {
                toggle_popover(tray.app_handle(), position);
            }
        });

    builder.build(app)?;
    Ok(())
}

fn handle_menu(app: &AppHandle, id: &str) {
    match id {
        "start_pause" => {
            let snap = {
                let state = app.state::<AppState>();
                let mut e = state.engine.lock().unwrap();
                if e.is_running() {
                    e.pause();
                } else {
                    e.start();
                }
                e.snapshot()
            };
            let _ = app.emit("tick", &snap);
            update_tray_title(app, &snap);
        }
        "reset" => {
            let app = app.clone();
            tauri::async_runtime::spawn(async move {
                let (snap, log) = {
                    let state = app.state::<AppState>();
                    let mut e = state.engine.lock().unwrap();
                    let log = e.reset();
                    (e.snapshot(), log)
                };
                if let Some(log) = log {
                    let pool = app.state::<AppState>().db.clone();
                    let _ = crate::db::log_session(&pool, &log).await;
                }
                let _ = app.emit("tick", &snap);
                update_tray_title(&app, &snap);
            });
        }
        "skip" => {
            let app = app.clone();
            tauri::async_runtime::spawn(async move {
                let (snap, result) = {
                    let state = app.state::<AppState>();
                    let mut e = state.engine.lock().unwrap();
                    let result = e.finish_phase(false);
                    (e.snapshot(), result)
                };
                let pool = app.state::<AppState>().db.clone();
                let _ = crate::db::log_session(&pool, &result.log).await;
                notify_phase_change(&app, &result.change);
                let _ = app.emit("phase-change", &result.change);
                let _ = app.emit("tick", &snap);
                update_tray_title(&app, &snap);
            });
        }
        "open_stats" => show_main(app, "stats"),
        "open_settings" => show_main(app, "settings"),
        "quit" => app.exit(0),
        _ => {}
    }
}

/// Popover width in logical pixels (matches tauri.conf.json).
const POPOVER_W: f64 = 320.0;
/// Approximate macOS menu-bar height in logical pixels.
const MENU_BAR_H: f64 = 24.0;

fn toggle_popover(app: &AppHandle, cursor: PhysicalPosition<f64>) {
    let Some(w) = app.get_webview_window("popover") else {
        return;
    };
    if w.is_visible().unwrap_or(false) {
        let _ = w.hide();
        return;
    }

    // Position manually (the positioner plugin panics on current_monitor().unwrap()
    // for a freshly shown window). Anchor to the monitor under the clicked tray
    // icon so it lands correctly on any display in a multi-monitor setup, centered
    // on the click and clamped within that monitor's bounds.
    let (x, y) = match w.monitor_from_point(cursor.x, cursor.y) {
        Ok(Some(mon)) => {
            let scale = mon.scale_factor();
            let mp = mon.position();
            let ms = mon.size();
            let win_w = (POPOVER_W * scale) as i32;
            let min_x = mp.x;
            let max_x = (mp.x + ms.width as i32 - win_w).max(min_x);
            let x = ((cursor.x as i32) - win_w / 2).clamp(min_x, max_x);
            let y = mp.y + (MENU_BAR_H * scale) as i32;
            (x, y)
        }
        // Fallback: best-effort relative to the cursor.
        _ => ((cursor.x as i32) - 160, (cursor.y as i32) + 8),
    };
    let _ = w.set_position(PhysicalPosition::new(x, y));
    let _ = w.show();
    let _ = w.set_focus();
}

pub fn show_main(app: &AppHandle, tab: &str) {
    if let Some(w) = app.get_webview_window("main") {
        let _ = w.show();
        let _ = w.set_focus();
        let _ = app.emit_to("main", "navigate", tab);
    }
}

/// macOS shows the tray title in the menu bar; on Windows it surfaces via the
/// tooltip. We set both so the live MM:SS is visible cross-platform.
pub fn update_tray_title(app: &AppHandle, snap: &TimerSnapshot) {
    if let Some(tray) = app.tray_by_id(TRAY_ID) {
        // Title is text only — the flat tray icon already represents the app, so
        // an emoji glyph here would show a second (color) tomato in the menu bar.
        let time = fmt_mmss(snap.remaining_secs);
        let _ = tray.set_title(Some(time.clone()));
        let _ = tray.set_tooltip(Some(format!("{} — {}", snap.phase.label(), time)));
    }
}

pub fn notify_phase_change(app: &AppHandle, change: &PhaseChange) {
    let body = if change.auto_started {
        format!(
            "{} finished. Starting {}.",
            change.ended_phase.label(),
            change.next_phase.label()
        )
    } else {
        format!(
            "{} finished. Next: {}.",
            change.ended_phase.label(),
            change.next_phase.label()
        )
    };
    let _ = app
        .notification()
        .builder()
        .title("Timelon")
        .body(body)
        .show();
}
